name: assignment_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

dependencies:
  args: ^2.3.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_rate_limiter: ^1.0.1
  content_length_validator: ^1.2.1
  shelf_helmet: ^2.2.0
  shelf_cors_headers: ^0.1.5
  supabase: ^2.0.1

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
  shelf_hotreload: ^1.4.0
  
